### ISSUE TITLE
github repo terraform module

### ISSUE THREAD

**Issue by fargozhu** [Nmbrs/tf-modules#119]
### Description

The ability to create github repositories with organization policies setup by default.

### Intended Outcome

- when creating a new repository, then the user must give a name.
- when creating a new repository, then the user can select a repository template.
- when creating a new repository, then all the repository settings are applied by default, following the org guidelines.

### Note(s)

- [Mineiros](https://github.com/mineiros-io/terraform-github-repository)

**Comment by filipefigueredo** [comment]
Shall we close this issue @pmmluis and @fargozhu ?
