### ISSUE TITLE
Fix code scanning alert - The minimum TLS version for Storage Accounts should be TLS1_2

### ISSUE THREAD

**Issue by fargozhu** [Nmbrs/tf-modules#43]
Tracking issue for:
- [ ] https://github.com/Nmbrs/tf-modules/security/code-scanning/2

**Comment by filipefigueredo** [comment]
After we merge PR #46 , will be fixed in PR #45

**Comment by filipefigueredo** [comment]
I'll close this issue since PR #45 was merged

**Comment by filipefigueredo** [comment]
I'll close this issue since PR #45 was merged
